### ISSUE TITLE
Not able to add more than 2 questions

### ISSUE THREAD

**Issue by AshokR** [vijayaraj/testyourtamilskills#1]
I added two questions. For adding the third question, when I press the add question button I get the following message:
15 கேள்விகள் சேர்த்துவிட்டீர்கள்! :)

**Comment by vijayaraj** [comment]
Fixed the issue.

**Comment by AshokR** [comment]
மிக்க நன்றி! வேகமாக வழு திருத்துவதில் இதுதான் சாதனை :+1:
